server:
  port: 8080

spring:
  application:
    name: hmdp-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hmdp-core-service
              uri: http://localhost:8085
              predicates:
                - Path=/user/**,/shop/**,/shop-type/**,/blog/**,/follow/**,/voucher/**,/voucher-order/**,/upload/**,/test/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
