server:
  port: 8080

spring:
  application:
    name: hmdp-gateway
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: hmdp-auth-service
              uri: http://localhost:8081
              predicates:
                - Path=/user/code,/user/login,/user/logout,/user/me
            - id: hmdp-user-service
              uri: http://localhost:8082
              predicates:
                - Path=/user/info/**,/user/level/update,/user/sign,/user/sign/count,/user/{id}
            - id: hmdp-core-service
              uri: http://localhost:8085
              predicates:
                - Path=/user/**,/shop/**,/shop-type/**,/blog/**,/follow/**,/voucher/**,/voucher-order/**,/upload/**,/test/**

management:
  endpoints:
    web:
      exposure:
        include: health,info

hmdp:
  gateway:
    auth:
      enabled: true
      login-user-key-prefix: "login:token:"
      token-ttl: 36000m
      whitelist:
        - /user/code
        - /user/login
        - /shop/**
        - /shop-type/**
        - /voucher/**
        - /blog/hot
        - /upload/**
        - /test/**
        - /actuator/**
